services:
    minecraft:
        image: itzg/minecraft-server:latest
        container_name: minecraft
        ports:
            - "25565:25565"
        environment:
            EULA: "TRUE"
            RCON_PASSWORD: "secretpassword"
            ENABLE_RCON: "true"
            SERVER_PORT: "25565"
            RCON_PORT: "25575"
            LEVEL: "Midgard"
        volumes:
            - ./minecraft-admin/data:/data
        restart: unless-stopped
        networks:
            - legangerweb-net

    mc-backend:
        build: ./minecraft-admin/backend
        container_name: mc-backend
        volumes:
            - ./minecraft-admin/backend/src:/app/src
        environment:
            RCON_HOST: minecraft
            RCON_PORT: 25575
            RCON_PASSWORD: secretpassword
        depends_on:
            - minecraft
        restart: unless-stopped
        networks:
            - legangerweb-net

    mc-frontend:
        build:
            context: ./minecraft-admin/frontend
            dockerfile: Dockerfile
        container_name: mc-frontend
        volumes:
            - ./minecraft-admin/frontend/src:/app/src
            - ./minecraft-admin/frontend/public:/app/public
            - ./minecraft-admin/frontend/index.html:/app/index.html
        depends_on:
            - mc-backend
        restart: unless-stopped
        networks:
            - legangerweb-net

networks:
    legangerweb-net:
        name: legangerweb-net
        external: true
