FROM alpine:latest

RUN apk add --no-cache \
    bash \
    nginx \
    curl \
    nodejs \
    npm \
    python3 \
    py3-pip \
    nano \
    vim \
    git \
    openssl \
    certbot \
    certbot-nginx \
    net-tools 

CMD [ "bash" ]