services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.temp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/nginx/html:/srv/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt:ro

    networks:
      - legangerweb-net

networks:
  legangerweb-net:
    name: legangerweb-net
    driver: bridge
